apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheusapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: cd/prometheus
    repoURL: 'https://github.com/prmiguel/todomvc-cicd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
