apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-mvc
  name: todo-mvc
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: todo-mvc
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-mvc
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: todomvc-angular
        resources: {}
        ports:
          - containerPort: 80
status: {}
